# Generated by fusen: do not edit by hand

#' say_hello A function to say hello
#'
#' @param someone the name of the person to say hello to (type = character)
#'
#' @importFrom glue glue
#' @return A message with Hello to someone giving their name
#' @export
#'
#' @examples
#' say_hello()
#' say_hello(someone = "Katerina")
say_hello <- function(someone = "You") {
 message(glue::glue("Hello {someone}"))
}
